language: cpp
compiler: gcc
dist: trusty
sudo: required

before_script:
# Download and unpack Urho3D SDK.
- echo $PWD
- wget http://downloads.sourceforge.net/project/urho3d/Urho3D/1.6/Urho3D-1.6-Linux-64bit-SHARED.tar.gz -O Urho3D.tar.gz
- tar -xvf Urho3D.tar.gz
- export URHO3D_HOME=$PWD/Urho3D-1.6-Linux-64bit-SHARED/usr/local
- echo $URHO3D_HOME
# Init XVFB.
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
# Download, build and install StatesEngine SDK
- LastPWD=$PWD
- git clone https://github.com/KonstantinTomashevich/states-engine-for-urho3d.git
- cd states-engine-for-urho3d
- mkdir build
- cd build
- cmake .. -DSTATES_ENGINE_INSTALL=1 -DCMAKE_INSTALL_PREFIX=$PWD/SDK
- make
- make install
- export STATES_ENGINE_SDK_DIR=$PWD/SDK
- cd $LastPWD

script:
- mkdir build 
- cd build 
- echo $URHO3D_HOME
- echo $STATES_ENGINE_SDK_DIR
- cmake .. -DSTATES_ENGINE_SDK=$STATES_ENGINE_SDK_DIR -DENABLE_TESTING=1 -DENGINE_ENABLE_ASSERTION=1 -DGAME_ENABLE_ASSERTION=1
- make 
- make test

after_failure:
# Print CTest files content.
- cd Testing
- cd Temporary
- cat CTestCostData.txt
- cat LastTest.txt
- cat LastTestsFailed.txt
- cd ..
- cd ..
- cd bin
- cat Urho3D.log
